### ISSUE TITLE
Allow mimetype extension lookup

### ISSUE THREAD

**Issue by EngineerCoding** [khellang/MimeTypes#10]
Allow to lookup the extension based on the MimeType please.

**Comment by khellang** [comment]
I'd gladly take a pull request for this 😄

**Comment by EngineerCoding** [comment]
Noted, will look into it the coming week if I have some time :)

**Comment by khellang** [comment]
Closed with #11

**Comment by khellang** [comment]
Pushed to NuGet with v2.2.0 😄

**Comment by forresthopkinsa** [comment]
Can you add this to the README please

**Comment by khellang** [comment]
@forresthopkinsa Done! https://github.com/khellang/MimeTypes#lookup-file-extension-by-mimemedia-type
