### ISSUE TITLE
Consolidating Efforts

### ISSUE THREAD

**Issue by TonyValenti** [khellang/MimeTypes#12]
Hi @khellang -
I am the new maintainer of:
https://www.nuget.org/packages/Mime-Detective/
https://github.com/MediatedCommunications/Mime-Detective

and have recently published an update expanding to over 14,000 mime signatures. Are you open to combining/joining efforts?
If so, can you add TonyValenti as a admin on the MimeTypes nuget package?

**Comment by khellang** [comment]
Hi @TonyValenti! 👋

> Are you open to combining/joining efforts?

What would that mean, exactly? 🤔

**Comment by TonyValenti** [comment]
What I would like to do is build an update to ```MimeTypes``` that leverages the data and definitions used by Mime-Detective.  There is a lot that could be shared between the two libraries.

**Comment by khellang** [comment]
I'd like to see more details, or possibly a PR outlining the changes you're suggesting.

This package is deliberately simple and ships a single .cs file as source. At runtime it's more or less a dictionary lookup. Generating the dictionary at build-time uses mime-db as source, which in turn aggregates IANA, apache and nginx.

Based on the above, I'm not sure what this package would gain by leveraging another package 🤔
