### ISSUE TITLE
Explicit namespaces

### ISSUE THREAD

**Issue by labtox** [khellang/MimeTypes#13]
Hello,

I try to use this package in Xamarin.Android, but I get build errors because of namespace issues.
![image](https://user-images.githubusercontent.com/4747477/130437128-8f7c6a5a-eb73-4d93-8c83-1efe734089c3.png)

If I edit the code file manually like this. it works:
![image](https://user-images.githubusercontent.com/4747477/130437252-0cbdd2a1-d4dd-45be-9ed9-d0c58042dc27.png)
I just prepended all the using statements at the top with "global::"

Another fix which works for me is moving the using statements out of the namespace declaration, like so:
![image](https://user-images.githubusercontent.com/4747477/130437555-f66eb810-9357-4cdf-873d-33d5545639f3.png)

If you could fix this one way or another, that would be awesome!

Regards,
labtox

**Comment by khellang** [comment]
Hello @labtox! 👋🏻 

Pushed v2.1.4 with a fix to NuGet 😄

**Comment by khellang** [comment]
I wonder why I haven't seen this before? Do you have an `AppCore.System` namespace?

**Comment by labtox** [comment]
Actually, we do have that namespace 😅 that's probably the case here

Thanks a lot for the quick response and fix 👍

**Comment by labtox** [comment]
One minor question...
Is there a reason it's pushed to 2.1.4, while there is also a 2.2.0 version available?

**Comment by khellang** [comment]
Ummm. That's weird. I might've pushed a version 2.2.0 earlier, but somehow forgotten to push the tag and version bump commit? 🤔 I'll push a v2.2.1 as well, so it's the latest 😅
