### ISSUE TITLE
GetMimeTypeExtensions should return string

### ISSUE THREAD

**Issue by naji-makhoul** [khellang/MimeTypes#28]
when trying to get MimeType in GetMimeTypeExtensions it's shuold rturn string or exciption if not exsits

now it's return IEnumerable<string> 
string fileExtension = MimeTypes.GetMimeTypeExtensions(mimeType).SingleOrDefault();

string fileExtension = MimeTypes.GetMimeTypeExtensions(mimeType); , will not compile
why need to use SingleOrDefault ?

**Comment by khellang** [comment]
It's named `GetMimeTypeExtensions` (plural) and returns an `IEnumerable` for a reason. A MIME/media type can map to many extensions. It's impossible for this library to pick one.
