### ISSUE TITLE
Throws "same key is already added exception"

### ISSUE THREAD

**Issue by otake1977** [khellang/MimeTypes#3]
There are duplicates on some of the extensions which fails the initialization of the dictionary:
( 'sub', 'image/vnd.dvb.subtitle' ),
( 'sub', 'text/vnd.dvb.subtitle' ),

and 

( 'wmz', 'application/x-ms-wmz' ),
( 'wmz', 'application/x-msmetafile' ),

**Comment by khellang** [comment]
Ouch! I'll take a look at it ASAP. Thanks! :+1:

**Comment by khellang** [comment]
Should be fixed with addb385cb63c0d7cbd381d43a0830ed07fa0039c, pushed a new version (v1.0.3).
