### ISSUE TITLE
Does not generate MimeTypes.cs in .NET Core project

### ISSUE THREAD

**Issue by asherber** [khellang/MimeTypes#5]
When the NuGet package is added to a .NET Core project, the `MimeTypes.cs` file does not get generated or added to the project.

**Comment by ramondeklein** [comment]
I guess this is related to https://github.com/NuGet/Home/issues/1086.

**Comment by asherber** [comment]
Yes, looks like content directories are no longer supported for projects that use `project.json` instead of a `.csproj` file. Maybe MimeTypes could deliver a traditional compiled assembly, instead of a source file? Or maybe this could be a separate NuGet package?

**Comment by khellang** [comment]
I've pushed a new version (v1.0.6), using NuGet's new [content files](http://blog.nuget.org/20160126/nuget-contentFiles-demystified.html) feature. I think these should work for the newer project formats as well. Want to give it a spin?

**Comment by asherber** [comment]
Hmm, not working for me in a .NET Core project -- I don't see a generated file.

**Comment by hey-red** [comment]
Same problem. Better to do with the traditional assembly with methods a la LookupExtension/LookupMimeType.

**Comment by khellang** [comment]
@asherber With NuGet content files, the files don't show up in Visual Studio. They're copied into the obj folder at build-time. The APIs should still show up in IntelliSense though.

**Comment by asherber** [comment]
I see that the .pp file is under the obj folder, but it doesn't appear to get compiled. IntelliSense is not working, either with `using MimeTypes;` or by fully qualifying the call, and the project won't compile.

But maybe some of that is due to other cruft in that project, so I tried again with a brand new .NET core project. I installed MimeTypes and compiled, and now I get:
```
1>------ Build started: Project: MimeTypes-Test, Configuration: Debug Any CPU ------
1>  C:\Program Files\dotnet\dotnet.exe build "P:\CSharpApps\Scratch\MimeTypes-Test" --configuration Debug --no-dependencies
1>  Project MimeTypes-Test (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
1>  Compiling MimeTypes-Test for .NETCoreApp,Version=v1.0
1>  C:\Program Files\dotnet\dotnet.exe compile-csc @P:\CSharpApps\Scratch\MimeTypes-Test\obj\Debug\netcoreapp1.0\dotnet-compile.rsp returned Exit Code 1
1>P:\CSharpApps\Scratch\MimeTypes-Test\obj\Debug\netcoreapp1.0\MimeTypes.cs.pp(4,21): error CS0116: A namespace cannot directly contain members such as fields or methods
1>P:\CSharpApps\Scratch\MimeTypes-Test\obj\Debug\netcoreapp1.0\MimeTypes.cs.pp(4,20): error CS1514: { expected
1>P:\CSharpApps\Scratch\MimeTypes-Test\obj\Debug\netcoreapp1.0\MimeTypes.cs.pp(5,1): error CS1022: Type or namespace definition, or end-of-file expected
1>  Compilation failed.
1>      0 Warning(s)
1>      3 Error(s)
1>  Time elapsed 00:00:01.3199878
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Projects build report:
  Status    | Project [Config|platform]
 -----------|---------------------------------------------------------------------------------------------------
  Failed    | MimeTypes-Test\MimeTypes-Test.xproj [Debug|Any CPU]

Time Elapsed 00:00:02.102
```

**Comment by khellang** [comment]
Hmm. It sounds like it didn't like the .cs.pp file. I'll see if I can figure something out...

**Comment by mduu** [comment]
1.0.6 is not working on .Net Core 2 on mac w. Visual Studio for Mac.

**Comment by khellang** [comment]
I think https://github.com/dotnet/sdk/issues/1100 might be the blocker here...

**Comment by khellang** [comment]
Any update here? Looks like https://github.com/dotnet/sdk/issues/1100 has been resolved.

**Comment by khellang** [comment]
I just tried installing this package (version 1.1.0) in a .NET Core 2.1 project and it worked fine. There's no file showing up, but you can call the API and it shows IntelliSense.

**Comment by darkguy2008** [comment]
2021, just installed the package, .NET 5, no way to use it. Any ideas? What's the namespace?

![image](https://user-images.githubusercontent.com/6304136/116775030-b3aa7b80-aa1d-11eb-8529-06a82b7a0e58.png)
