### ISSUE TITLE
Add comments or change rootnamespace

### ISSUE THREAD

**Issue by bdebaere** [khellang/MimeTypes#7]
Because you are using `namespace $rootnamespace$` I currently cannot enable XML documentation in combination with treat warnings as errors. Since some things aren't commented.

Would it be possible to either add comments or change the namespace?

**Comment by khellang** [comment]
Good point! I'll get some XML docs added to the public members!

**Comment by khellang** [comment]
Pushed a new version, v1.1.0, which should get rid of all warnings 😄
